#define TK_LP                              1
#define TK_RP                              2
#define TK_SEMI                            3
#define TK_EXPLAIN                         4
#define TK_QUERY                           5
#define TK_PLAN                            6
#define TK_BEGIN                           7
#define TK_START                           8
#define TK_TRANSACTION                     9
#define TK_WORK                           10
#define TK_COMMIT                         11
#define TK_ROLLBACK                       12
#define TK_CREATE                         13
#define TK_TABLE                          14
#define TK_IF                             15
#define TK_NOT                            16
#define TK_EXISTS                         17
#define TK_TEMP                           18
#define TK_AS                             19
#define TK_COMMA                          20
#define TK_ID                             21
#define TK_EQ                             22
#define TK_DEFAULT                        23
#define TK_CHARSET                        24
#define TK_SET                            25
#define TK_COLLATE                        26
#define TK_ABORT                          27
#define TK_AFTER                          28
#define TK_ANALYZE                        29
#define TK_ASC                            30
#define TK_ATTACH                         31
#define TK_BEFORE                         32
#define TK_CASCADE                        33
#define TK_CAST                           34
#define TK_CONFLICT                       35
#define TK_DATABASE                       36
#define TK_DEFERRED                       37
#define TK_DESC                           38
#define TK_DETACH                         39
#define TK_EACH                           40
#define TK_END                            41
#define TK_EXCLUSIVE                      42
#define TK_FAIL                           43
#define TK_FOR                            44
#define TK_IGNORE                         45
#define TK_IMMEDIATE                      46
#define TK_INITIALLY                      47
#define TK_INSTEAD                        48
#define TK_LIKE_KW                        49
#define TK_MATCH                          50
#define TK_KEY                            51
#define TK_OF                             52
#define TK_OFFSET                         53
#define TK_PRAGMA                         54
#define TK_RAISE                          55
#define TK_REPLACE                        56
#define TK_RESTRICT                       57
#define TK_ROW                            58
#define TK_STATEMENT                      59
#define TK_TRIGGER                        60
#define TK_VACUUM                         61
#define TK_VIEW                           62
#define TK_REINDEX                        63
#define TK_RENAME                         64
#define TK_CTIME_KW                       65
#define TK_OR                             66
#define TK_AND                            67
#define TK_IS                             68
#define TK_BETWEEN                        69
#define TK_IN                             70
#define TK_ISNULL                         71
#define TK_NOTNULL                        72
#define TK_NE                             73
#define TK_GT                             74
#define TK_LE                             75
#define TK_LT                             76
#define TK_GE                             77
#define TK_ESCAPE                         78
#define TK_BITAND                         79
#define TK_BITOR                          80
#define TK_LSHIFT                         81
#define TK_RSHIFT                         82
#define TK_PLUS                           83
#define TK_MINUS                          84
#define TK_STAR                           85
#define TK_SLASH                          86
#define TK_REM                            87
#define TK_CONCAT                         88
#define TK_UMINUS                         89
#define TK_UPLUS                          90
#define TK_BITNOT                         91
#define TK_STRING                         92
#define TK_JOIN_KW                        93
#define TK_CONSTRAINT                     94
#define TK_AUTOINCR                       95
#define TK_NULL                           96
#define TK_PRIMARY                        97
#define TK_UNIQUE                         98
#define TK_CHECK                          99
#define TK_REFERENCES                     100
#define TK_ON                             101
#define TK_DELETE                         102
#define TK_UPDATE                         103
#define TK_INSERT                         104
#define TK_DEFERRABLE                     105
#define TK_FOREIGN                        106
#define TK_DROP                           107
#define TK_UNION                          108
#define TK_ALL                            109
#define TK_EXCEPT                         110
#define TK_INTERSECT                      111
#define TK_SELECT                         112
#define TK_DISTINCT                       113
#define TK_DOT                            114
#define TK_FROM                           115
#define TK_JOIN                           116
#define TK_USING                          117
#define TK_ORDER                          118
#define TK_BY                             119
#define TK_GROUP                          120
#define TK_HAVING                         121
#define TK_LIMIT                          122
#define TK_WHERE                          123
#define TK_INTO                           124
#define TK_VALUES                         125
#define TK_INTEGER                        126
#define TK_FLOAT                          127
#define TK_BLOB                           128
#define TK_REGISTER                       129
#define TK_VARIABLE                       130
#define TK_VARIABLE1                      131
#define TK_CASE                           132
#define TK_WHEN                           133
#define TK_THEN                           134
#define TK_ELSE                           135
#define TK_TO_TEXT                        136
#define TK_TO_BLOB                        137
#define TK_TO_NUMERIC                     138
#define TK_TO_INT                         139
#define TK_TO_REAL                        140
#define TK_END_OF_FILE                    141
#define TK_ILLEGAL                        142
#define TK_SPACE                          143
#define TK_UNCLOSED_STRING                144
#define TK_COMMENT                        145
#define TK_FUNCTION                       146
#define TK_COLUMN                         147
#define TK_AGG_FUNCTION                   148
#define TK_AGG_COLUMN                     149
#define TK_CONST_FUNC                     150
