/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_matrix_openglleak_detector */

#ifndef _Included_com_tencent_matrix_openglleak_detector_FuncSeeker
#define _Included_com_tencent_mm_openglapihook_FuncSeeker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_matrix_openglleak_detector_FuncSeeker
 * Method:    getGlGetErrorIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tencent_matrix_openglleak_detector_FuncSeeker_getGlGetErrorIndex
        (JNIEnv *, jclass);

/*
 * Class:     com_tencent_matrix_openglleak_detector_FuncSeeker
 * Method:    getGenFuncIndex
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_matrix_openglleak_detector_FuncSeeker_getTargetFuncIndex
        (JNIEnv *, jclass, jstring);


extern "C"
JNIEXPORT jint JNICALL
Java_com_tencent_matrix_openglleak_detector_FuncSeeker_getBindFuncIndex(JNIEnv *env, jclass clazz,
                                                                        jstring bind_func_name);

extern "C"
JNIEXPORT jint JNICALL
Java_com_tencent_matrix_openglleak_detector_FuncSeeker_getGlTexImage2DIndex(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
