/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_matrix_openglleak_statistics_OpenGLInfo */

#ifndef _Included_com_tencent_matrix_openglleak_statistics_OpenGLInfo
#define _Included_com_tencent_matrix_openglleak_statistics_OpenGLInfo
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_tencent_mm_openglapihook_OpenGLHook
* Method:    init
* Signature: ()Z
*/
JNIEXPORT void JNICALL Java_com_tencent_matrix_openglleak_statistics_OpenGLInfo_releaseNative
        (JNIEnv *, jobject thiz, jlong);

JNIEXPORT jstring JNICALL Java_com_tencent_matrix_openglleak_statistics_OpenGLInfo_dumpNativeStack
        (JNIEnv *, jclass thiz, jlong);

#ifdef __cplusplus
}
#endif
#endif
